//Alunas: Gabriela Sena da Silva e Luisa Pedrolli      2ºTI

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.registro;

/**
 *
 * @author Gabriela
 */

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class jFTabelaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form jFTabelaRegistro
     */
    public jFTabelaRegistro() {
        initComponents();
        //MUDAR TABELA AUTOMATICA
        jTProdutos.setModel(tabelaproduto); // faz a tabela rodar e fazer mudanças que eu faço
        try {
            SQLConexao.carregarRegistros(tabelaproduto);
        } catch (SQLException ex) {
            Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAdicionar = new javax.swing.JButton();
        jBRemover = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBRecuperar = new javax.swing.JButton();
        jBLimparTela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTPreço = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jBGravarArquivo = new javax.swing.JButton();
        jTCaminhoDoArquivo = new javax.swing.JTextField();
        jBLerArquivo = new javax.swing.JButton();
        jBCaminhoDoArquivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        jBTestarConexao = new javax.swing.JButton();
        jTTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBRemover.setText("Remover");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBRecuperar.setText("Recuperar");
        jBRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecuperarActionPerformed(evt);
            }
        });

        jBLimparTela.setText("Limpar Tela");
        jBLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparTelaActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod");

        jLabel2.setText("Produto");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Preço");

        jBGravarArquivo.setText("Gravar Arquivo");
        jBGravarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarArquivoActionPerformed(evt);
            }
        });

        jBLerArquivo.setText("Ler Arquivo");
        jBLerArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLerArquivoActionPerformed(evt);
            }
        });

        jBCaminhoDoArquivo.setText("Caminho do Arquivo");
        jBCaminhoDoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCaminhoDoArquivoActionPerformed(evt);
            }
        });

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTProdutos);

        jBTestarConexao.setText("Testar Conexão");
        jBTestarConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTestarConexaoActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTCod, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jBRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jBRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBLimparTela, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 27, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBGravarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBCaminhoDoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jBLerArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBTestarConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTCaminhoDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionar)
                    .addComponent(jBRemover)
                    .addComponent(jBAlterar)
                    .addComponent(jBRecuperar)
                    .addComponent(jBLimparTela))
                .addGap(18, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCaminhoDoArquivo)
                    .addComponent(jTCaminhoDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGravarArquivo)
                    .addComponent(jBLerArquivo)
                    .addComponent(jBTestarConexao))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed
        // TODO add your handling code here:
        int linha = jTProdutos.getSelectedRow();
        if(linha != -1){
            try {
                SQLConexao.deletarRegistro((int)tabelaproduto.getValueAt(linha,0));
                tabelaproduto.removerProduto(linha);
                
            } catch (SQLException ex) {
                Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }

    }//GEN-LAST:event_jBRemoverActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        // TODO add your handling code here:
        if(jTProdutos.getSelectedRow() != -1){
            
            String nomeProduto = jTNomeProduto.getText();
            int cod = Integer.parseInt(jTCod.getText());
            int quantidade = Integer.parseInt(jTQuantidade.getText());
            double preco = Double.parseDouble(jTPreço.getText());
            String tipo= jTTipo.getText();
            
            try {
                SQLConexao.alterarRegistro(nomeProduto, quantidade, preco,tipo, cod);
            } catch (SQLException ex) {
                Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Produto produto = new Produto(cod,nomeProduto ,quantidade, preco,tipo);
            
            tabelaproduto.alterarProduto(produto, jTProdutos.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
        limparCampos();
        
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecuperarActionPerformed
        // TODO add your handling code here:
        
         if(jTProdutos.getSelectedRow() != -1){
            jTCod.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0).toString());
            jTNomeProduto.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
            jTQuantidade.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
            jTPreço.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());
            jTTipo.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
         
    }//GEN-LAST:event_jBRecuperarActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        // TODO add your handling code here:
        String nomeProduto = jTNomeProduto.getText();
        int quantidade = Integer.parseInt(jTQuantidade.getText());
        double preco = Double.parseDouble(jTPreço.getText());
        String tipo = jTTipo.getText();
        
        Produto produto = new Produto(nomeProduto, quantidade, preco,tipo);
       
        
        try {
            SQLConexao.adicionarProduto(produto);
            tabelaproduto.adicionarProduto(produto);
        } catch (SQLException ex) {
            Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não inseriu!");
        }
        limparCampos();
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBGravarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarArquivoActionPerformed
        // TODO add your handling code here:
        
    if(caminho.length()>0){
            try{
                arquivo = new File(caminho);
                arquivo.createNewFile();
                JOptionPane.showMessageDialog(null, "Arquivo salvo com sucesso!");
            }
            catch(IOException e){
                System.err.println(e);
            }
            
            FileWriter escrita = null;
            
        try {
            escrita = new FileWriter(arquivo);
        } catch (IOException ex) {
            Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
             
            PrintWriter escritaFormatada = new PrintWriter(escrita);
            
            for(int linha = 0; linha < tabelaproduto.getRowCount(); linha++ ){
                Produto produto = tabelaproduto.getProduto(linha); 
                
                int cod = produto.getCod();
                String nomeProduto = produto.getNomeProduto();
                int quantidade = produto.getQuantidade();
                double preco = produto.getPreco();
                String tipo = produto.getTipo();
                
                escritaFormatada.printf("%d / %s / %d / %.2f / %s %n", cod, nomeProduto, quantidade, preco,tipo);
            }
            
            try {
                escrita.close();
            } catch (IOException ex) {
                Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBGravarArquivoActionPerformed

    private void jBLerArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLerArquivoActionPerformed
        // TODO add your handling code here:
        
        Scanner leitura = null;
        
        if(caminho.length() > 0){
            try {
                leitura = new Scanner(Paths.get(caminho));
                
            } catch (IOException ex) {
                Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            while(leitura.hasNextLine()){
                
                String linha = leitura.nextLine();
                System.out.println(linha);
                
                String[] palavras = linha.split(" / "); //delimita as plavras em cada posicao pela /
                
                int cod= Integer.parseInt(palavras[0]);
                String nomeProduto = palavras[1];
                int quantidade= Integer.parseInt(palavras[2]);
                double preco = Double.parseDouble(palavras[3].replace(',','.'));
                String tipo = palavras[4];
        
                Produto produto = new Produto(cod, nomeProduto, quantidade, preco,tipo);
        
                tabelaproduto.adicionarProduto(produto);
            }
            JOptionPane.showMessageDialog(null, "Arquivo lido com sucesso!");
        }
    }//GEN-LAST:event_jBLerArquivoActionPerformed

    private void jBCaminhoDoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCaminhoDoArquivoActionPerformed
       
        JFileChooser selecaoArquivo = new JFileChooser();
        selecaoArquivo.showOpenDialog(this);
        System.out.println(selecaoArquivo.getSelectedFile().getPath());
        caminho = selecaoArquivo.getSelectedFile().getPath();
        jTCaminhoDoArquivo.setText(caminho);
        
    }//GEN-LAST:event_jBCaminhoDoArquivoActionPerformed

    private void jBLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparTelaActionPerformed
        // TODO add your handling code here:
       tabelaproduto.limparTabela();
    }//GEN-LAST:event_jBLimparTelaActionPerformed

    private void jBTestarConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTestarConexaoActionPerformed
        // TODO add your handling code here:
        
        boolean conectado = false;
        
        try {
            SQLConexao.getConexao();
            conectado = true;
        } catch (SQLException ex) {
            Logger.getLogger(jFTabelaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(conectado){
            JOptionPane.showMessageDialog(null, "Conectado com sucesso!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Conexao falhou!");
        }
    }//GEN-LAST:event_jBTestarConexaoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFTabelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFTabelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFTabelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFTabelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFTabelaRegistro().setVisible(true);
            }
        });
    }
    
    private void limparCampos(){
        jTCod.setText("");
        jTNomeProduto.setText("");
        jTQuantidade.setText("");
        jTPreço.setText("");
        jTTipo.setText("");
        jTCod.requestFocus();
    }
    
    private String caminho = "";
    private File arquivo = null;
    private ProdutoTableModel tabelaproduto = new ProdutoTableModel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCaminhoDoArquivo;
    private javax.swing.JButton jBGravarArquivo;
    private javax.swing.JButton jBLerArquivo;
    private javax.swing.JButton jBLimparTela;
    private javax.swing.JButton jBRecuperar;
    private javax.swing.JButton jBRemover;
    private javax.swing.JButton jBTestarConexao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCaminhoDoArquivo;
    private javax.swing.JTextField jTCod;
    private javax.swing.JTextField jTNomeProduto;
    private javax.swing.JTextField jTPreço;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JTextField jTQuantidade;
    private javax.swing.JTextField jTTipo;
    // End of variables declaration//GEN-END:variables
}
